name: Package Application with PyInstaller

on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.8.3"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed for poetry dynamic versioning.
          # If possible, would be best to fetch till last git tag instead of entire history.
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Inject poetry-pyinstaller-plugin
        run: pipx inject poetry poetry-pyinstaller-plugin
      - name: Inject poetry-dynamic-versioning
        run: pipx inject poetry "poetry-dynamic-versioning[plugin]"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Build package
        run: poetry build --format pyinstaller
      - uses: actions/upload-artifact@v4
        with:
          name: pymusiclooper-${{ matrix.os }}
          path: |
            dist/pyinstaller/**/*
            !dist/pyinstaller/**/.specs
